package com.myspace.health_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class claims implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("firstName")
	private java.lang.String firstName;
	@org.kie.api.definition.type.Label("lastName")
	private java.lang.String lastName;
	@org.kie.api.definition.type.Label("policyNumber")
	private java.lang.String policyNumber;
	@org.kie.api.definition.type.Label("mongoDocID")
	private java.lang.String mongoDocID;
	@org.kie.api.definition.type.Label("claimAmount")
	private java.lang.Integer claimAmount;

	@org.kie.api.definition.type.Label(value = "decision")
	private java.lang.String decision;

	public claims() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getMongoDocID() {
		return this.mongoDocID;
	}

	public void setMongoDocID(java.lang.String mongoDocID) {
		this.mongoDocID = mongoDocID;
	}

	public java.lang.Integer getClaimAmount() {
		return this.claimAmount;
	}

	public void setClaimAmount(java.lang.Integer claimAmount) {
		this.claimAmount = claimAmount;
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public claims(java.lang.String firstName, java.lang.String lastName,
			java.lang.String policyNumber, java.lang.String mongoDocID,
			java.lang.Integer claimAmount, java.lang.String decision) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.policyNumber = policyNumber;
		this.mongoDocID = mongoDocID;
		this.claimAmount = claimAmount;
		this.decision = decision;
	}

}